""" Application GUI configurations """


# Main window
APP_MAINWINDOW_TITLE = 'XXXChange'
APP_MAINWINDOW_MIN_WIDTH = 800
APP_MAINWINDOW_MIN_HEIGHT = 600


# About window
ABOUT_WINDOW_TITLE = ''
ABOUT_WINDOW_WIDTH = 600
ABOUT_WINDOW_HEIGHT = 400