# Global configuartion

[author]
name = "Abhijith E A"
email = "abhijithea3773@gmail.com"

[database.mysql]
user = "root"
host = "127.0.0.1"
port = 3306
password = 12345678

[database.sqlite]
user = ''
host = ''